<ol class="layer-color-filter">
<?php foreach ($this->getItems() as $_item): ?>
    <li class="inline-block-item bg-color-<?php echo strtolower($_item->getLabel()) ?> <?php echo $_item->isSelected() === true ? 'selected' : ''; ?>" style="background-color: <?php echo strtolower($_item->getLabel()) ?>;">
        <?php if ($_item->getCount() > 0): ?>
            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                <?php echo $_item->getLabel() ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            </a>
        <?php else: ?>
            <span class="inline-block-item bg-color-<?php echo strtolower($_item->getLabel()) ?>">
                <?php echo $_item->getLabel(); ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
